use_frameworks!

platform :ios, '9.0'

target 'CodesDancing_Example' do
  pod 'CodesDancing', :path => '../'

  target 'CodesDancing_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
